name: Build and Deploy Docker image

on:
  push:
    branches:
      - main # Trigger this workflow only for push events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Set the context to the root directory of your repo
          file: .dockerfile # Specify the Dockerfile name explicitly using 'file'
          push: true
          tags: nathan14224/whatsapp-integration:latest
